# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actistream", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                name="notice",
                fields=("user", "read_at"),
            ),
        )
    ]
